# Generated by Django 2.2.13 on 2020-11-16 20:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20201116_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='referencia_pasarela',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Referencia de la Pasarela'),
        ),
        migrations.AddField(
            model_name='venta',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='referencia',
            field=models.CharField(default=1, editable=False, max_length=150, unique=True, verbose_name='Referencia'),
            preserve_default=False,
        ),
    ]
