# Generated by Django 2.2.13 on 2020-11-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_venta_tipo_pasarela'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Total'),
        ),
    ]
