# Generated by Django 2.2.13 on 2020-11-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_venta_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaproducts',
            name='especificaciones',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Especificaciones del producto'),
        ),
    ]
