# Generated by Django 2.2.13 on 2020-11-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_ventaproducts_especificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaproducts',
            name='by_venta_caja',
            field=models.BooleanField(default=False, verbose_name='Venta de Caja'),
        ),
    ]
