# Generated by Django 2.2.13 on 2020-11-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_ventaproducts_by_venta_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaproducts',
            name='by_venta_caja',
            field=models.BooleanField(default=False, verbose_name='Cantidad de Caja'),
        ),
    ]
