# Generated by Django 3.1.4 on 2021-01-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_auto_20201126_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('proceso', 'Proceso'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('espera_respuesta_pasarela', 'Respuesta de Pasarela'), ('error_pasarela', 'Error en la Pasarela')], default='proceso', max_length=45, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Metodo de Pago'),
        ),
        migrations.AddField(
            model_name='venta',
            name='transaccion_id',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Transaccion de la Pasarela'),
        ),
    ]
