# Generated by Django 3.1.3 on 2021-03-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_ventaproducts_by_mayor'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='razon_rechazado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('proceso', 'Proceso'), ('aprobado', 'Aprobado'), ('pendiente_efectivo', 'Pendiente Pago Efectivo'), ('rechazado', 'Rechazado'), ('espera_respuesta_pasarela', 'Respuesta de Pasarela'), ('error_pasarela', 'Error en la Pasarela')], default='proceso', max_length=45, verbose_name='Estado'),
        ),
    ]
