# Generated by Django 2.2 on 2020-07-02 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('enlace', models.URLField(blank=True, default='', null=True, verbose_name='Enlace')),
                ('imagen', models.ImageField(blank=True, default='', null=True, upload_to='uploads/farsali/backgrounds/', verbose_name='Imagen')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Background',
                'verbose_name_plural': 'Backgrounds',
                'ordering': ('orden',),
            },
        ),
        migrations.CreateModel(
            name='Farsali',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='uploads/farsali/farsali/', verbose_name='Logo Farsali')),
                ('email', models.EmailField(help_text='Correo electrónico de contacto', max_length=254, verbose_name='Email')),
                ('latitud', models.FloatField(default=0.0, verbose_name='Latitud')),
                ('longitud', models.FloatField(default=0.0, verbose_name='Longitud')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Farsali',
                'verbose_name_plural': 'Farsalis',
                'ordering': ('orden',),
            },
        ),
        migrations.CreateModel(
            name='Generic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, verbose_name='Código')),
                ('titulo', models.CharField(max_length=75, verbose_name='Título')),
                ('enlace', models.URLField(blank=True, default='', null=True, verbose_name='Enlace')),
                ('imagen', models.ImageField(blank=True, default='', null=True, upload_to='uploads/farsali/imagenes/', verbose_name='Imagen')),
                ('subtitulo', models.CharField(max_length=100, verbose_name='Subtítulo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Generic',
                'verbose_name_plural': 'Generics',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlace', models.URLField(blank=True, default='', null=True, verbose_name='Enlace')),
                ('codigo', models.CharField(max_length=100, verbose_name='Código')),
                ('titulo', models.CharField(max_length=75, verbose_name='Título')),
                ('imagen', models.ImageField(blank=True, default='', null=True, upload_to='uploads/farsali/imagenes/', verbose_name='Imagen')),
                ('subtitulo', models.CharField(max_length=100, verbose_name='Subtítulo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
                'ordering': ('orden',),
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='uploads/farsali/marcas/', verbose_name='Logo Marca')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ('orden',),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, verbose_name='Título')),
                ('codigo', models.CharField(max_length=15, verbose_name='Codigo')),
                ('imagen', models.ImageField(upload_to='uploads/videos/', verbose_name='Imagen')),
                ('origen', models.SmallIntegerField(choices=[(0, 'Youtube'), (1, 'Vimeo')], default=0, verbose_name='Origen')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ('orden',),
            },
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[['TW', 'Twitter'], ['FB', 'Facebook'], ['11870', '11870'], ['YTB', 'Youtube'], ['GP', 'Google+'], ['WP', 'Wordpress'], ['FR', 'Flickr'], ['PT', 'Pinterest'], ['FS', 'Foursquare'], ['TA', 'Tripadvisor'], ['LI', 'LinkedIn'], ['IN', 'Instagram'], ['VINE', 'Vine'], ['TUM', 'Tumblr'], ['VIM', 'Vimeo'], ['BL', 'Blog']], default='TW', max_length=10, verbose_name='Tipo')),
                ('url', models.URLField(blank=True, default='', null=True, verbose_name='URL')),
                ('codigo', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Código')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('farsali', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farsaliredsocial_set', to='apps.Farsali', verbose_name='Farsali Red Social')),
            ],
            options={
                'verbose_name': 'Red social',
                'verbose_name_plural': 'Redes sociales',
                'ordering': ('orden', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='GaleriaGeneric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre')),
                ('imagen', models.ImageField(max_length=200, upload_to='uploads/cms_apps/imagenes/', verbose_name='Imagen')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('generic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genericgaleria_set', to='apps.Generic', verbose_name='Noticia')),
            ],
            options={
                'verbose_name': 'Galeria generics',
                'verbose_name_plural': 'Galería de Generics',
                'ordering': ('orden',),
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('farsali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farsalicontacto_set', to='apps.Farsali', verbose_name='Contacto Farsali')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ('orden',),
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(0, 'Pendiente de aprovación'), (1, 'Comentario aprovado'), (2, 'Comentario denegado')], default=1, verbose_name='Estado')),
                ('comentario', models.TextField(default='', max_length=1000, verbose_name='Comentario')),
                ('titulo', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Título')),
                ('nombre', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('localizador', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Localizador')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ('orden',),
            },
        ),
    ]
