# Generated by Django 2.2.13 on 2020-11-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_delete_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='contenido',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido'),
        ),
    ]
