# Generated by Django 2.2.13 on 2020-11-13 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_contacto_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='farsali',
        ),
        migrations.RemoveField(
            model_name='redsocial',
            name='farsali',
        ),
        migrations.DeleteModel(
            name='Farsali',
        ),
    ]
