# Generated by Django 2.2.13 on 2020-11-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20201113_1751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
