# Generated by Django 2.2.13 on 2020-11-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_delete_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasarelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.SmallIntegerField(choices=[(0, 'MercadoPago'), (1, 'Wompi')], default=0, verbose_name='Origen')),
                ('activo', models.BooleanField(default=False, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Pasarela',
                'verbose_name_plural': 'Pasarelas',
            },
        ),
    ]
