# Generated by Django 2.2.13 on 2020-11-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_pasarelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasarelas',
            name='origen',
            field=models.SmallIntegerField(choices=[(0, 'MercadoPago'), (1, 'Wompi')], default=0, unique=True, verbose_name='Origen'),
        ),
    ]
