# Generated by Django 2.2.13 on 2020-11-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20201116_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farsali',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('contrasena', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100, verbose_name='Teléfono')),
                ('edad', models.PositiveIntegerField(default=0, verbose_name='Edad')),
                ('locacion', models.CharField(max_length=100, verbose_name='Locación')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
                ('email', models.EmailField(help_text='Correo electrónico de contacto', max_length=254, verbose_name='Email')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Farsali',
                'verbose_name_plural': 'Farsalis',
                'ordering': ('orden',),
            },
        ),
    ]
