# Generated by Django 2.2.13 on 2020-11-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_farsali'),
    ]

    operations = [
        migrations.AddField(
            model_name='farsali',
            name='nick_name',
            field=models.CharField(default='algo', max_length=100, unique=True, verbose_name='Nick Name'),
            preserve_default=False,
        ),
    ]
