# Generated by Django 2.2.13 on 2020-11-19 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_farsali_nick_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Farsali',
        ),
    ]
