# Generated by Django 2.2.13 on 2020-11-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_delete_farsali'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='video',
            field=models.CharField(default='', max_length=100, verbose_name='Video'),
            preserve_default=False,
        ),
    ]
