# Generated by Django 2.2.13 on 2020-11-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_auto_20201121_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='En minúsculas. Como si fuera un atributo del propio proyecto. Se accede con un __get__ de proyecto.', max_length=30, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('str', 'Cadena'), ('int', 'Entero'), ('list', 'Lista'), ('dict', 'Diccionario'), ('bool', 'Boleano'), ('datetime', 'Fecha/Hora')], default='str', max_length=10, verbose_name='Tipo')),
                ('valor', models.TextField(verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Constante',
                'verbose_name_plural': 'Constantes',
            },
        ),
    ]
