# Generated by Django 2.2.13 on 2020-11-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_constante'),
    ]

    operations = [
        migrations.AddField(
            model_name='constante',
            name='enlace_texto',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='constante',
            name='nombre',
            field=models.CharField(help_text='En minúsculas. Como si fuera un atributo', max_length=30, verbose_name='Nombre'),
        ),
    ]
