# Generated by Django 2.2.13 on 2020-11-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_auto_20201123_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='redsocial',
            name='icono',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/farsali/red_social/', verbose_name='Ícono'),
        ),
        migrations.AddField(
            model_name='redsocial',
            name='icono_svg',
            field=models.FileField(blank=True, null=True, upload_to='uploads/farsali/red_social/', verbose_name='Ícono SVG'),
        ),
        migrations.AddField(
            model_name='redsocial',
            name='nombre',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='redsocial',
            name='url',
            field=models.URLField(default='', verbose_name='URL'),
            preserve_default=False,
        ),
    ]
