# Generated by Django 2.2.13 on 2020-11-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_auto_20201125_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='background',
            name='nombre',
        ),
        migrations.AddField(
            model_name='background',
            name='subtitulo',
            field=models.CharField(default='', max_length=100, verbose_name='Subtítulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='background',
            name='titulo',
            field=models.CharField(default='', max_length=100, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
