# Generated by Django 2.2.13 on 2020-11-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_auto_20201125_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='constante',
            name='icono',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/farsali/constantes/', verbose_name='Ícono'),
        ),
        migrations.AddField(
            model_name='constante',
            name='icono_svg',
            field=models.FileField(blank=True, null=True, upload_to='uploads/farsali/constantes/', verbose_name='Ícono SVG'),
        ),
    ]
