# Generated by Django 2.2.13 on 2020-11-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_auto_20201125_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='background',
            options={'ordering': ('orden',), 'verbose_name': 'Imagen Principal', 'verbose_name_plural': 'Imágenes Principales'},
        ),
    ]
