# Generated by Django 3.1.3 on 2020-12-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_auto_20201126_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasarelas',
            name='origen',
            field=models.SmallIntegerField(choices=[(0, 'MercadoPago'), (1, 'Wompi'), (2, 'Epayco')], default=0, unique=True, verbose_name='Origen'),
        ),
    ]
