# Generated by Django 2.2 on 2020-06-17 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('url', models.SlugField(max_length=100, verbose_name='Url')),
                ('imagen', models.ImageField(blank=True, default='', null=True, upload_to='uploads/inventario/imagenes/', verbose_name='Foto categoría')),
            ],
            options={
                'verbose_name': 'Categoría Producto',
                'verbose_name_plural': 'Categorías Productos',
                'ordering': ('orden',),
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=39, unique=True, verbose_name='Código')),
                ('url', models.SlugField(blank=True, default='', max_length=100, null=True, verbose_name='Url')),
                ('nombre', models.CharField(max_length=75, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('marca', models.CharField(max_length=75, verbose_name='Marca')),
                ('imagen', models.ImageField(blank=True, default='', null=True, upload_to='uploads/inventario/imagenes/', verbose_name='Foto')),
                ('costo', models.FloatField(default=0.0, verbose_name='Costo')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('destacado', models.BooleanField(db_index=True, default=True, verbose_name='Destacado')),
                ('calificacion', models.IntegerField(blank=True, choices=[('0', '1 estrella'), ('2', '2 estrella'), ('3', '3 estrella'), ('4', '4 estrella'), ('5', '5 estrella')], null=True, verbose_name='Calificacion')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_set', to='inventario.CategoriaProducto', verbose_name='Categoría Producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ('orden',),
            },
        ),
    ]
