# Generated by Django 2.2.13 on 2020-10-24 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20200912_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre')),
                ('imagen', models.ImageField(max_length=200, upload_to='uploads/cms_apps/imagenes/', verbose_name='Imagen')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria_producto', to='inventario.Producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen Producto',
                'verbose_name_plural': 'Galería de Productos',
            },
        ),
    ]
