# Generated by Django 2.2.13 on 2020-10-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_producto_codigo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_video',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Código video YouTube'),
        ),
    ]
