# Generated by Django 2.2.13 on 2020-10-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20201025_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeriaproducto',
            name='imagen',
            field=models.ImageField(max_length=200, upload_to='uploads/inventario/imagenes/', verbose_name='Imagen'),
        ),
    ]
