# Generated by Django 2.2.13 on 2020-11-13 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20201025_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentariosProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('ciudad', models.CharField(max_length=250, verbose_name='Ciudad')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_producto', to='inventario.Producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Comentario Producto',
                'verbose_name_plural': 'Comentarios de Productos',
            },
        ),
    ]
