# Generated by Django 2.2.13 on 2020-11-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_comentariosproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariosproducto',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
