# Generated by Django 2.2.13 on 2020-11-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_comentariosproducto_activo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComentariosProducto',
        ),
    ]
