# Generated by Django 2.2.13 on 2020-11-13 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_delete_comentariosproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(0, 'Pendiente de aprovación'), (1, 'Comentario aprovado'), (2, 'Comentario denegado')], default=1, verbose_name='Estado')),
                ('comentario', models.TextField(default='', max_length=1000, verbose_name='Comentario')),
                ('titulo', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Título')),
                ('nombre', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('localizador', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Localizador')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ('orden',),
            },
        ),
    ]
