# Generated by Django 2.2.13 on 2020-11-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_farsali',
            field=models.FloatField(default=0.0, verbose_name='Costo Farsali'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Pendiente de aprobación'), (1, 'Comentario aprobado'), (2, 'Comentario denegado')], default=1, verbose_name='Estado'),
        ),
    ]
