# Generated by Django 2.2.13 on 2020-11-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_auto_20201113_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Ciudad'),
        ),
    ]
