# Generated by Django 2.2.13 on 2020-11-14 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_comentario_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario_producto', to='inventario.Producto', verbose_name='Producto'),
        ),
    ]
