# Generated by Django 2.2.13 on 2020-11-16 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_auto_20201113_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('tipo_marca', models.SmallIntegerField(choices=[(0, 'Marca Farsali'), (1, 'Marca Original')], default=0, verbose_name='Tipo de Marca')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='uploads/farsali/marcas/', verbose_name='Logo Marca')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ('orden',),
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Pendiente de aprobación'), (1, 'Comentario aprobado'), (2, 'Comentario denegado')], default=0, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marca_producto', to='inventario.Marca', verbose_name='Marca Producto'),
        ),
    ]
