# Generated by Django 2.2.13 on 2020-11-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_auto_20201116_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='tipo_marca',
            field=models.SmallIntegerField(choices=[(0, 'Farsali'), (1, 'Original')], default=0, verbose_name='Tipo de Marca'),
        ),
    ]
