# Generated by Django 2.2.13 on 2020-11-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_auto_20201116_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_cajas',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad x Cajas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveIntegerField(verbose_name='Cantidad Individual'),
        ),
    ]
