# Generated by Django 3.1.3 on 2020-12-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_auto_20201125_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion_prefer',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion del producto prefer'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveIntegerField(verbose_name='Cantidad en almacén'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion del producto'),
        ),
    ]
