# Generated by Django 3.1.3 on 2020-12-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_producto_descripcion_no_prefer'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_adicional',
            field=models.FloatField(default=0.0, verbose_name='Costo Adicional'),
        ),
    ]
