# Generated by Django 3.1.3 on 2020-12-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_producto_descripcion_adicional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion_adicional',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion Adicional del producto'),
        ),
    ]
