# Generated by Django 3.1.3 on 2021-01-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_auto_20201229_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_cajas_prefer',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad x Cajas Farsali'),
        ),
    ]
