# Generated by Django 3.1.3 on 2021-02-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_auto_20210222_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='tipo_marca',
            field=models.SmallIntegerField(choices=[(0, 'Original Farsáli Colombia'), (1, 'Marcas Autorizadas')], default=0, verbose_name='Tipo de Marca'),
        ),
    ]
