# Generated by Django 3.1.3 on 2021-02-28 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0028_auto_20210225_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje del descuento')),
                ('nombre', models.CharField(max_length=340)),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Activar'), (2, 'Desactivar')], default=1)),
                ('fecha_expiration', models.DateField(blank=True, null=True)),
                ('prioridad', models.IntegerField(default=0, verbose_name='prioridad')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('categorias_productos', models.ManyToManyField(related_name='descuento_productos', to='inventario.CategoriaProducto', verbose_name='CategoriaProducto')),
                ('productos', models.ManyToManyField(related_name='descuento_productos', to='inventario.Producto', verbose_name='Producto')),
            ],
        ),
    ]
