# Generated by Django 3.1.3 on 2021-03-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0030_auto_20210307_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuentos',
            name='categorias_productos',
            field=models.ManyToManyField(blank=True, null=True, related_name='descuento_categorias', to='inventario.CategoriaProducto', verbose_name='CategoriaProducto'),
        ),
    ]
