# Generated by Django 3.1.3 on 2021-03-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0031_auto_20210308_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descuentos',
            options={'ordering': ('prioridad', 'creado')},
        ),
        migrations.AddField(
            model_name='producto',
            name='by_producto_prefer',
            field=models.BooleanField(default=False, verbose_name='Producto Prefer'),
        ),
        migrations.AlterField(
            model_name='descuentos',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Activado'), (2, 'Desactivado')], default=1),
        ),
    ]
