# Generated by Django 3.1.3 on 2021-04-12 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0032_auto_20210317_2244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Descuentos',
            new_name='Descuento',
        ),
    ]
