# Generated by Django 3.1.3 on 2021-04-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0034_auto_20210423_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriaproducto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
