# Generated by Django 3.1.3 on 2021-05-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0036_auto_20210429_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriaproducto',
            name='enlace',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Enlace'),
        ),
    ]
