# Generated by Django 3.1.3 on 2021-05-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0037_galeriaproducto_enlace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeriaproducto',
            name='imagen',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='uploads/inventario/imagenes/', verbose_name='Imagen'),
        ),
    ]
