# Generated by Django 3.1.3 on 2021-05-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0038_auto_20210513_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_cajas_farsali',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad x Cajas Mayor Prefer'),
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_prefer',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad x Cajas Prefer'),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_caja_prefer',
            field=models.FloatField(default=0.0, verbose_name='Costo Prefer Mayor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_prefer',
            field=models.FloatField(default=0.0, verbose_name='Costo Prefer'),
        ),
    ]
