# Generated by Django 3.1.3 on 2021-05-19 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0039_auto_20210519_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_cajas_farsali',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_prefer',
        ),
    ]
