# Generated by Django 2.2 on 2020-06-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(help_text='Correo electrónico de contacto', max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(max_length=100, verbose_name='Teléfono')),
                ('is_farsali', models.BooleanField(db_index=True, default=True, verbose_name='Es cliente Farsali')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(editable=False, verbose_name='Fecha creación')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ('orden',),
            },
        ),
    ]
