# Generated by Django 2.2.13 on 2020-11-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20201118_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contrasena',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
