# Generated by Django 2.2.13 on 2020-11-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_activacion',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de activación'),
        ),
    ]
