# Generated by Django 2.2.13 on 2020-11-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_fecha_activacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Cédula'),
            preserve_default=False,
        ),
    ]
